### ISSUE TITLE
Resource unavailable error

### ISSUE THREAD

**Issue by masukomi** [ahdinosaur/ssb-pub#3]
After running the digital ocean one click installer and getting no UI i attempted to run the server (found it in a thread on ssb) 

```
root@ssb-pub:~# ./sbot server
flumelog-offset: blockSize and codec params moved into an object. https://github.com/flumedb/flumelog-offset
Log level: notice

events.js:183
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: lock /home/node/.ssb/db/LOCK: Resource temporarily unavailable
    at /home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/level-packager/node_modules/levelup/lib/levelup.js:117:34
    at /home/node/.npm-global/lib/node_modules/scuttlebot/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
root@ssb-pub:~#
```

it should be noted that `/home/node` is not a valid directory via normal means even though the erroring code seems to be there. Maybe this is some aspect of docker that i don't understand (i'm pretty ignorant about docker)

```
$ ls /home/
debian
```

also, the first time i ran it i hit control+c after a minute or two of it seeming to not be doing anything at all and yet not giving me a prompt back. maybe i borked something by doing that?

**Comment by ahdinosaur** [comment]
hey @masukomi, this is erroring because `sbot server` is already running. there's no ui you're missing out on, if there was i would have said something about it in the instructions. a ui for generating invites would be sweet though!

**Comment by masukomi** [comment]
ok so, i'm totally confused then (putting this here for the next confused person). When i  click on the link to a pub from the wiki, there's a web ui.  Where does that come from and how do i turn it on?

**Comment by ahdinosaur** [comment]
hey @masukomi, yeah sorry for quick answer above, just woke up. you're thinking of [staltz/easy-ssb-pub](https://github.com/staltz/easy-ssb-pub), which is a similar but different ssb pub setup that also runs a ui for automatically generating invites. i used to use that for @ssb.rootsystems.nz, which helped get us at least a few thousand new people on-board, but i found the setup more unreliable and harder for me to fix, plus i want to transition away from pubs with automatic invites to more personal ecosystem growth.
