### ISSUE TITLE
Please update docker build (or it will be removed under new Docker Hub terms)

### ISSUE THREAD

**Issue by sunjam** [ahdinosaur/ssb-pub#38]
Please make any minor change to the Docker build.  Docker Hub has changed TOS to say any project with no development after two calendar years is to be removed from the platform.

Thanks!

**Comment by ahdinosaur** [comment]
thanks for the notice @sunjam, will update now!

as there's also been a significant bug that likely affects everyone using `ssb-pub`. :sweat_smile: `%5JJIwkud9hizK8Bb2WYznfgKnRyHhrG5YBbw830d68Y=.sha256`

**Comment by ahdinosaur** [comment]
updated! https://github.com/ahdinosaur/ssb-pub/issues/37#issuecomment-724441578 :cake:
