### ISSUE TITLE
Question about Advanced Setup

### ISSUE THREAD

**Issue by zachmandeville** [ahdinosaur/ssb-pub#4]
Hey hey hey!  This is cool!

I read through the Readme, and found installing the pub on digital ocean a (digital ocean)breeze!  
I also registered a site and domain at thesolarpunk.club.  What I'd like to do is host a pub at pub.thesolarpunk.club and so my invites are coming from there instead of a random ip string.

In the Readme the advanced setup section seems to be for this use case, but it was unclear to me whether this setup was separate from the ssb-pub installer.  Like, would I run through those debian commands while ssh'ed into my digital ocean droplet?  Or would I have to host the site pub.thesolarpunk.club somewhere else that had a debian server, ssh into there, and then run through the commands?  If it is the former, do I need to point this domain to my digital ocean droplet first, through some other method?

Thank you!

**Comment by zachmandeville** [comment]
(Side note: It makes sense to me that I could do this all on my DO Droplet, once I point my domain to it.  I'm following the DO instructions for that, and if successful I can make a pull request for links on how to do that, if you'd think that'd be helpful!)

**Comment by ahdinosaur** [comment]
> In the Readme the advanced setup section seems to be for this use case, but it was unclear to me whether this setup was separate from the ssb-pub installer.

yes, the advanced setup is for a fresh DigitalOcean server running Debian!
